stages:
  - build
  - test

variables:
  ESLINT_NO_RC: "yes"
  # ESLINT_DISABLED: ""

# Default example build job (copied from gitlab example)
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

# Custom eslint job
custom-eslint:
  stage: test
  image: node
  script:
    - echo "Installing ESLint..."
    - npm install eslint
    - echo "Installation complete. Running linter..."
    - |
      if [[ -n "${ESLINT_NO_RC}" ]]; then
        echo "Info - ESLint configuration file disabled."
      else
        echo "Info - Using repository configuration file."
      fi
    - ./node_modules/.bin/eslint ${ESLINT_NO_RC:+'--no-eslintrc'} .
  rules:
    - if: '$ESLINT_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
